@startuml
digraph test {

        "libonig5
(6.9.4-1)" -> "libc6
(2.31-0ubuntu9.15)"
        "jq
(1.6-1ubuntu0.20.04.1)" -> "libjq1
(1.6-1ubuntu0.20.04.1)"
        "jq
(1.6-1ubuntu0.20.04.1)" -> "libc6
(2.31-0ubuntu9.15)"
        "libjq1
(1.6-1ubuntu0.20.04.1)" -> "libc6
(2.31-0ubuntu9.15)"
        "libjq1
(1.6-1ubuntu0.20.04.1)" -> "libonig5
(6.9.4-1)"
        "libc6
(2.31-0ubuntu9.15)" -> "libcrypt1
(1:4.4.10-10ubuntu4)"
        "libc6
(2.31-0ubuntu9.15)" -> "libgcc-s1
(10.5.0-1ubuntu1~20.04)"
        "libgcc-s1
(10.5.0-1ubuntu1~20.04)" -> "gcc-10-base
(10.5.0-1ubuntu1~20.04)"
        "libgcc-s1
(10.5.0-1ubuntu1~20.04)" -> "libc6
(2.31-0ubuntu9.15)"

}

@enduml